require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TeamGoalsController do

  # This should return the minimal set of attributes required to create a valid
  # TeamGoal. As you add validations to TeamGoal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "team" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TeamGoalsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all team_goals as @team_goals" do
      team_goal = TeamGoal.create! valid_attributes
      get :index, {}, valid_session
      assigns(:team_goals).should eq([team_goal])
    end
  end

  describe "GET show" do
    it "assigns the requested team_goal as @team_goal" do
      team_goal = TeamGoal.create! valid_attributes
      get :show, {:id => team_goal.to_param}, valid_session
      assigns(:team_goal).should eq(team_goal)
    end
  end

  describe "GET new" do
    it "assigns a new team_goal as @team_goal" do
      get :new, {}, valid_session
      assigns(:team_goal).should be_a_new(TeamGoal)
    end
  end

  describe "GET edit" do
    it "assigns the requested team_goal as @team_goal" do
      team_goal = TeamGoal.create! valid_attributes
      get :edit, {:id => team_goal.to_param}, valid_session
      assigns(:team_goal).should eq(team_goal)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TeamGoal" do
        expect {
          post :create, {:team_goal => valid_attributes}, valid_session
        }.to change(TeamGoal, :count).by(1)
      end

      it "assigns a newly created team_goal as @team_goal" do
        post :create, {:team_goal => valid_attributes}, valid_session
        assigns(:team_goal).should be_a(TeamGoal)
        assigns(:team_goal).should be_persisted
      end

      it "redirects to the created team_goal" do
        post :create, {:team_goal => valid_attributes}, valid_session
        response.should redirect_to(TeamGoal.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved team_goal as @team_goal" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeamGoal.any_instance.stub(:save).and_return(false)
        post :create, {:team_goal => { "team" => "invalid value" }}, valid_session
        assigns(:team_goal).should be_a_new(TeamGoal)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeamGoal.any_instance.stub(:save).and_return(false)
        post :create, {:team_goal => { "team" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested team_goal" do
        team_goal = TeamGoal.create! valid_attributes
        # Assuming there are no other team_goals in the database, this
        # specifies that the TeamGoal created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TeamGoal.any_instance.should_receive(:update).with({ "team" => "" })
        put :update, {:id => team_goal.to_param, :team_goal => { "team" => "" }}, valid_session
      end

      it "assigns the requested team_goal as @team_goal" do
        team_goal = TeamGoal.create! valid_attributes
        put :update, {:id => team_goal.to_param, :team_goal => valid_attributes}, valid_session
        assigns(:team_goal).should eq(team_goal)
      end

      it "redirects to the team_goal" do
        team_goal = TeamGoal.create! valid_attributes
        put :update, {:id => team_goal.to_param, :team_goal => valid_attributes}, valid_session
        response.should redirect_to(team_goal)
      end
    end

    describe "with invalid params" do
      it "assigns the team_goal as @team_goal" do
        team_goal = TeamGoal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeamGoal.any_instance.stub(:save).and_return(false)
        put :update, {:id => team_goal.to_param, :team_goal => { "team" => "invalid value" }}, valid_session
        assigns(:team_goal).should eq(team_goal)
      end

      it "re-renders the 'edit' template" do
        team_goal = TeamGoal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeamGoal.any_instance.stub(:save).and_return(false)
        put :update, {:id => team_goal.to_param, :team_goal => { "team" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested team_goal" do
      team_goal = TeamGoal.create! valid_attributes
      expect {
        delete :destroy, {:id => team_goal.to_param}, valid_session
      }.to change(TeamGoal, :count).by(-1)
    end

    it "redirects to the team_goals list" do
      team_goal = TeamGoal.create! valid_attributes
      delete :destroy, {:id => team_goal.to_param}, valid_session
      response.should redirect_to(team_goals_url)
    end
  end

end
